# Generated by Django 5.2.12 on 2026-03-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'ordering': ['employee_id']},
        ),
        migrations.DeleteModel(
            name='EducationRecord',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
