# Generated by Django 5.2.7 on 2025-10-11 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cycle_type', models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_review_cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_hours', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'training_programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('CONSTRUCTIVE', 'Constructive'), ('GENERAL', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_shared_with_employee', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='employees.employee')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='employees.employee')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_assessment', models.TextField(blank=True)),
                ('self_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('manager_feedback', models.TextField(blank=True)),
                ('manager_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('technical_skills_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('communication_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('teamwork_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('leadership_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('problem_solving_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Expectations'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_EMPLOYEE', 'Pending Employee'), ('PENDING_MANAGER', 'Pending Manager'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('employee_acknowledgment', models.BooleanField(default=False)),
                ('employee_acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to='employees.employee')),
                ('review_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancereviewcycle')),
            ],
            options={
                'db_table': 'performance_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'review_cycle')},
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ENROLLED', max_length=20)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='employees.employee')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='performance.trainingprogram')),
            ],
            options={
                'db_table': 'training_enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('training_program', 'employee')},
            },
        ),
    ]
