# Generated by Django 5.2.12 on 2026-03-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_workexperience_employee_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_income'],
            },
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='allowance_type',
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='overtime_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='retirement_fund',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='tax',
        ),
        migrations.AddField(
            model_name='bonus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='name',
            field=models.CharField(default='bonus', max_length=255),
        ),
        migrations.AddField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('PERFORMANCE', 'Performance Bonus'), ('ANNUAL', 'Annual Bonus'), ('FESTIVAL', 'Festival Bonus'), ('PROJECT', 'Project Bonus'), ('REFERRAL', 'Referral Bonus'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='bonus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payrollperiod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payslip',
            table=None,
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('HRA', 'House Rent Allowance'), ('TA', 'Travel Allowance'), ('DA', 'Dearness Allowance'), ('MEDICAL', 'Medical Allowance'), ('SPECIAL', 'Special Allowance'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('TAX', 'Income Tax'), ('INSURANCE', 'Insurance'), ('PF', 'Provident Fund'), ('LOAN', 'Loan Repayment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(choices=[('BASIC', 'Basic Salary'), ('ALLOWANCE', 'Allowance'), ('BONUS', 'Bonus'), ('OVERTIME', 'Overtime'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payroll.payslip')),
            ],
        ),
        migrations.DeleteModel(
            name='AllowanceType',
        ),
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
    ]
