# Generated by Django 5.2.12 on 2026-03-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False},
        ),
    ]
