# Generated by Django 5.2.12 on 2026-03-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0002_remove_workexperience_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='is_mandatory',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employee'),
        ),
        migrations.AlterModelTable(
            name='holiday',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workschedule',
            table=None,
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__user__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
